// JavaScript wrapper for vtkGraphLayoutView with embind 
//
// This file was auto-generated using :
/*
node /home/jmh/github/VTKCMake/build/library/VTK-prefix/src/VTK-build/bin/vtkWrapJavaScript.js \
 @/home/jmh/github/VTKCMake/build/library/VTK-prefix/src/VTK-build/CMakeFiles/vtkViewsInfovis.js/vtkViewsInfovis.js.Release.args \
 -o \
 /home/jmh/github/VTKCMake/build/library/VTK-prefix/src/VTK-build/CMakeFiles/vtkViewsInfovis.js/vtkGraphLayoutViewEmbinding.cxx \
 /home/jmh/github/vtk/Views/Infovis/vtkGraphLayoutView.h
*/
#include "vtkEmbindSmartPointerTrait.h"
#include <emscripten.h>
#include <string>
#include "vtkVariant.h"
#include "vtkObjectBase.h"
#include "vtkIndent.h"
#include "vtkGraphLayoutStrategy.h"
#include "vtkEdgeLayoutStrategy.h"
#include "vtkGraphLayoutView.h"

template<> void emscripten::internal::raw_destructor<vtkGraphLayoutView>(vtkGraphLayoutView * ptr){ ptr->Delete(); }
EMSCRIPTEN_BINDINGS(vtkGraphLayoutView_class) {
  emscripten::class_<vtkGraphLayoutView, emscripten::base<vtkRenderView>>("vtkGraphLayoutView")
    .smart_ptr<vtkSmartPointer<vtkGraphLayoutView>>("vtkSmartPointer<vtkGraphLayoutView>")
    .constructor(&vtk::MakeVTKSmartPtr<vtkGraphLayoutView>)
    .class_function("IsTypeOf", emscripten::optional_override([]( const std::string & arg_0) -> int {  return vtkGraphLayoutView::IsTypeOf( arg_0.c_str());}))
    .function("IsA", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0) -> int {  return self.IsA( arg_0.c_str());}))
    .class_function("SafeDownCast", &vtkGraphLayoutView::SafeDownCast, emscripten::allow_raw_pointers())
    .function("NewInstance", &vtkGraphLayoutView::NewInstance, emscripten::allow_raw_pointers())
    .class_function("GetNumberOfGenerationsFromBaseType", emscripten::optional_override([]( const std::string & arg_0) -> int {  return vtkGraphLayoutView::GetNumberOfGenerationsFromBaseType( arg_0.c_str());}))
    .function("GetNumberOfGenerationsFromBase", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0) -> int {  return self.GetNumberOfGenerationsFromBase( arg_0.c_str());}))
    .function("SetVertexLabelArrayName", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0) -> void {  return self.SetVertexLabelArrayName( arg_0.c_str());}))
    .function("GetVertexLabelArrayName", emscripten::optional_override([](vtkGraphLayoutView& self) -> std::string {  return self.GetVertexLabelArrayName();}))
    .function("SetEdgeLabelArrayName", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0) -> void {  return self.SetEdgeLabelArrayName( arg_0.c_str());}))
    .function("GetEdgeLabelArrayName", emscripten::optional_override([](vtkGraphLayoutView& self) -> std::string {  return self.GetEdgeLabelArrayName();}))
    .function("SetVertexLabelVisibility", &vtkGraphLayoutView::SetVertexLabelVisibility)
    .function("GetVertexLabelVisibility", &vtkGraphLayoutView::GetVertexLabelVisibility)
    .function("VertexLabelVisibilityOn", &vtkGraphLayoutView::VertexLabelVisibilityOn)
    .function("VertexLabelVisibilityOff", &vtkGraphLayoutView::VertexLabelVisibilityOff)
    .function("SetHideVertexLabelsOnInteraction", &vtkGraphLayoutView::SetHideVertexLabelsOnInteraction)
    .function("GetHideVertexLabelsOnInteraction", &vtkGraphLayoutView::GetHideVertexLabelsOnInteraction)
    .function("HideVertexLabelsOnInteractionOn", &vtkGraphLayoutView::HideVertexLabelsOnInteractionOn)
    .function("HideVertexLabelsOnInteractionOff", &vtkGraphLayoutView::HideVertexLabelsOnInteractionOff)
    .function("SetEdgeVisibility", &vtkGraphLayoutView::SetEdgeVisibility)
    .function("GetEdgeVisibility", &vtkGraphLayoutView::GetEdgeVisibility)
    .function("EdgeVisibilityOn", &vtkGraphLayoutView::EdgeVisibilityOn)
    .function("EdgeVisibilityOff", &vtkGraphLayoutView::EdgeVisibilityOff)
    .function("SetEdgeLabelVisibility", &vtkGraphLayoutView::SetEdgeLabelVisibility)
    .function("GetEdgeLabelVisibility", &vtkGraphLayoutView::GetEdgeLabelVisibility)
    .function("EdgeLabelVisibilityOn", &vtkGraphLayoutView::EdgeLabelVisibilityOn)
    .function("EdgeLabelVisibilityOff", &vtkGraphLayoutView::EdgeLabelVisibilityOff)
    .function("SetHideEdgeLabelsOnInteraction", &vtkGraphLayoutView::SetHideEdgeLabelsOnInteraction)
    .function("GetHideEdgeLabelsOnInteraction", &vtkGraphLayoutView::GetHideEdgeLabelsOnInteraction)
    .function("HideEdgeLabelsOnInteractionOn", &vtkGraphLayoutView::HideEdgeLabelsOnInteractionOn)
    .function("HideEdgeLabelsOnInteractionOff", &vtkGraphLayoutView::HideEdgeLabelsOnInteractionOff)
    .function("SetVertexColorArrayName", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0) -> void {  return self.SetVertexColorArrayName( arg_0.c_str());}))
    .function("GetVertexColorArrayName", emscripten::optional_override([](vtkGraphLayoutView& self) -> std::string {  return self.GetVertexColorArrayName();}))
    .function("SetColorVertices", &vtkGraphLayoutView::SetColorVertices)
    .function("GetColorVertices", &vtkGraphLayoutView::GetColorVertices)
    .function("ColorVerticesOn", &vtkGraphLayoutView::ColorVerticesOn)
    .function("ColorVerticesOff", &vtkGraphLayoutView::ColorVerticesOff)
    .function("SetEdgeColorArrayName", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0) -> void {  return self.SetEdgeColorArrayName( arg_0.c_str());}))
    .function("GetEdgeColorArrayName", emscripten::optional_override([](vtkGraphLayoutView& self) -> std::string {  return self.GetEdgeColorArrayName();}))
    .function("SetColorEdges", &vtkGraphLayoutView::SetColorEdges)
    .function("GetColorEdges", &vtkGraphLayoutView::GetColorEdges)
    .function("ColorEdgesOn", &vtkGraphLayoutView::ColorEdgesOn)
    .function("ColorEdgesOff", &vtkGraphLayoutView::ColorEdgesOff)
    .function("SetEdgeSelection", &vtkGraphLayoutView::SetEdgeSelection)
    .function("GetEdgeSelection", &vtkGraphLayoutView::GetEdgeSelection)
    .function("EdgeSelectionOn", &vtkGraphLayoutView::EdgeSelectionOn)
    .function("EdgeSelectionOff", &vtkGraphLayoutView::EdgeSelectionOff)
    .function("SetEnabledEdgesArrayName", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0) -> void {  return self.SetEnabledEdgesArrayName( arg_0.c_str());}))
    .function("GetEnabledEdgesArrayName", emscripten::optional_override([](vtkGraphLayoutView& self) -> std::string {  return self.GetEnabledEdgesArrayName();}))
    .function("SetEnableEdgesByArray", &vtkGraphLayoutView::SetEnableEdgesByArray)
    .function("GetEnableEdgesByArray", &vtkGraphLayoutView::GetEnableEdgesByArray)
    .function("SetEnabledVerticesArrayName", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0) -> void {  return self.SetEnabledVerticesArrayName( arg_0.c_str());}))
    .function("GetEnabledVerticesArrayName", emscripten::optional_override([](vtkGraphLayoutView& self) -> std::string {  return self.GetEnabledVerticesArrayName();}))
    .function("SetEnableVerticesByArray", &vtkGraphLayoutView::SetEnableVerticesByArray)
    .function("GetEnableVerticesByArray", &vtkGraphLayoutView::GetEnableVerticesByArray)
    .function("SetScalingArrayName", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0) -> void {  return self.SetScalingArrayName( arg_0.c_str());}))
    .function("GetScalingArrayName", emscripten::optional_override([](vtkGraphLayoutView& self) -> std::string {  return self.GetScalingArrayName();}))
    .function("SetScaledGlyphs", &vtkGraphLayoutView::SetScaledGlyphs)
    .function("GetScaledGlyphs", &vtkGraphLayoutView::GetScaledGlyphs)
    .function("ScaledGlyphsOn", &vtkGraphLayoutView::ScaledGlyphsOn)
    .function("ScaledGlyphsOff", &vtkGraphLayoutView::ScaledGlyphsOff)
    .function("SetLayoutStrategy", emscripten::select_overload<void(vtkGraphLayoutView&, const std::string &)>([](vtkGraphLayoutView& self, const std::string & arg_0) -> void { return self.SetLayoutStrategy( arg_0.c_str()); }))
    .function("SetLayoutStrategy", emscripten::select_overload<void(vtkGraphLayoutView&, vtkGraphLayoutStrategy*)>([](vtkGraphLayoutView& self, vtkGraphLayoutStrategy* arg_0) -> void { return self.SetLayoutStrategy( arg_0); }), emscripten::allow_raw_pointers())
    .function("SetLayoutStrategyToRandom", &vtkGraphLayoutView::SetLayoutStrategyToRandom)
    .function("SetLayoutStrategyToForceDirected", &vtkGraphLayoutView::SetLayoutStrategyToForceDirected)
    .function("SetLayoutStrategyToSimple2D", &vtkGraphLayoutView::SetLayoutStrategyToSimple2D)
    .function("SetLayoutStrategyToClustering2D", &vtkGraphLayoutView::SetLayoutStrategyToClustering2D)
    .function("SetLayoutStrategyToCommunity2D", &vtkGraphLayoutView::SetLayoutStrategyToCommunity2D)
    .function("SetLayoutStrategyToFast2D", &vtkGraphLayoutView::SetLayoutStrategyToFast2D)
    .function("SetLayoutStrategyToPassThrough", &vtkGraphLayoutView::SetLayoutStrategyToPassThrough)
    .function("SetLayoutStrategyToCircular", &vtkGraphLayoutView::SetLayoutStrategyToCircular)
    .function("SetLayoutStrategyToTree", &vtkGraphLayoutView::SetLayoutStrategyToTree)
    .function("SetLayoutStrategyToCosmicTree", &vtkGraphLayoutView::SetLayoutStrategyToCosmicTree)
    .function("SetLayoutStrategyToCone", &vtkGraphLayoutView::SetLayoutStrategyToCone)
    .function("SetLayoutStrategyToSpanTree", &vtkGraphLayoutView::SetLayoutStrategyToSpanTree)
    .function("GetLayoutStrategyName", emscripten::optional_override([](vtkGraphLayoutView& self) -> std::string {  return self.GetLayoutStrategyName();}))
    .function("GetLayoutStrategy", &vtkGraphLayoutView::GetLayoutStrategy, emscripten::allow_raw_pointers())
    .function("SetEdgeLayoutStrategy", emscripten::select_overload<void(vtkGraphLayoutView&, const std::string &)>([](vtkGraphLayoutView& self, const std::string & arg_0) -> void { return self.SetEdgeLayoutStrategy( arg_0.c_str()); }))
    .function("SetEdgeLayoutStrategy", emscripten::select_overload<void(vtkGraphLayoutView&, vtkEdgeLayoutStrategy*)>([](vtkGraphLayoutView& self, vtkEdgeLayoutStrategy* arg_0) -> void { return self.SetEdgeLayoutStrategy( arg_0); }), emscripten::allow_raw_pointers())
    .function("SetEdgeLayoutStrategyToArcParallel", &vtkGraphLayoutView::SetEdgeLayoutStrategyToArcParallel)
    .function("SetEdgeLayoutStrategyToPassThrough", &vtkGraphLayoutView::SetEdgeLayoutStrategyToPassThrough)
    .function("GetEdgeLayoutStrategyName", emscripten::optional_override([](vtkGraphLayoutView& self) -> std::string {  return self.GetEdgeLayoutStrategyName();}))
    .function("GetEdgeLayoutStrategy", &vtkGraphLayoutView::GetEdgeLayoutStrategy, emscripten::allow_raw_pointers())
    .function("AddIconType", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0, int arg_1) -> void {  return self.AddIconType( arg_0.c_str(), arg_1);}))
    .function("ClearIconTypes", &vtkGraphLayoutView::ClearIconTypes)
    .function("SetIconAlignment", &vtkGraphLayoutView::SetIconAlignment)
    .function("SetIconVisibility", &vtkGraphLayoutView::SetIconVisibility)
    .function("GetIconVisibility", &vtkGraphLayoutView::GetIconVisibility)
    .function("IconVisibilityOn", &vtkGraphLayoutView::IconVisibilityOn)
    .function("IconVisibilityOff", &vtkGraphLayoutView::IconVisibilityOff)
    .function("SetIconArrayName", emscripten::optional_override([](vtkGraphLayoutView& self, const std::string & arg_0) -> void {  return self.SetIconArrayName( arg_0.c_str());}))
    .function("GetIconArrayName", emscripten::optional_override([](vtkGraphLayoutView& self) -> std::string {  return self.GetIconArrayName();}))
    .function("SetGlyphType", &vtkGraphLayoutView::SetGlyphType)
    .function("GetGlyphType", &vtkGraphLayoutView::GetGlyphType)
    .function("SetVertexLabelFontSize", &vtkGraphLayoutView::SetVertexLabelFontSize)
    .function("GetVertexLabelFontSize", &vtkGraphLayoutView::GetVertexLabelFontSize)
    .function("SetEdgeLabelFontSize", &vtkGraphLayoutView::SetEdgeLabelFontSize)
    .function("GetEdgeLabelFontSize", &vtkGraphLayoutView::GetEdgeLabelFontSize)
    .function("SetEdgeScalarBarVisibility", &vtkGraphLayoutView::SetEdgeScalarBarVisibility)
    .function("GetEdgeScalarBarVisibility", &vtkGraphLayoutView::GetEdgeScalarBarVisibility)
    .function("SetVertexScalarBarVisibility", &vtkGraphLayoutView::SetVertexScalarBarVisibility)
    .function("GetVertexScalarBarVisibility", &vtkGraphLayoutView::GetVertexScalarBarVisibility)
    .function("ZoomToSelection", &vtkGraphLayoutView::ZoomToSelection)
    .function("IsLayoutComplete", &vtkGraphLayoutView::IsLayoutComplete)
    .function("UpdateLayout", &vtkGraphLayoutView::UpdateLayout);
}
