// JavaScript wrapper for vtkMeshQuality with embind 
//
// This file was auto-generated using :
/*
node /home/jmh/github/VTKCMake/build/library/VTK-prefix/src/VTK-build/bin/vtkWrapJavaScript.js \
 @/home/jmh/github/VTKCMake/build/library/VTK-prefix/src/VTK-build/CMakeFiles/vtkFiltersVerdict.js/vtkFiltersVerdict.js.Release.args \
 -o \
 /home/jmh/github/VTKCMake/build/library/VTK-prefix/src/VTK-build/CMakeFiles/vtkFiltersVerdict.js/vtkMeshQualityEmbinding.cxx \
 /home/jmh/github/vtk/Filters/Verdict/vtkMeshQuality.h
*/
#include "vtkEmbindSmartPointerTrait.h"
#include <emscripten.h>
#include <string>
#include "vtkVariant.h"
#include "vtkIndent.h"
#include "vtkObjectBase.h"
#include "vtkCell.h"
#include "vtkMeshQuality.h"

EMSCRIPTEN_BINDINGS(vtkFiltersVerdict_vtkMeshQuality_class_enums) {
  emscripten::enum_<vtkMeshQuality::QualityMeasureTypes>("vtkMeshQuality_QualityMeasureTypes")
    .value("AREA", vtkMeshQuality::QualityMeasureTypes::AREA)
    .value("ASPECT_FROBENIUS", vtkMeshQuality::QualityMeasureTypes::ASPECT_FROBENIUS)
    .value("ASPECT_GAMMA", vtkMeshQuality::QualityMeasureTypes::ASPECT_GAMMA)
    .value("ASPECT_RATIO", vtkMeshQuality::QualityMeasureTypes::ASPECT_RATIO)
    .value("COLLAPSE_RATIO", vtkMeshQuality::QualityMeasureTypes::COLLAPSE_RATIO)
    .value("CONDITION", vtkMeshQuality::QualityMeasureTypes::CONDITION)
    .value("DIAGONAL", vtkMeshQuality::QualityMeasureTypes::DIAGONAL)
    .value("DIMENSION", vtkMeshQuality::QualityMeasureTypes::DIMENSION)
    .value("DISTORTION", vtkMeshQuality::QualityMeasureTypes::DISTORTION)
    .value("EDGE_RATIO", vtkMeshQuality::QualityMeasureTypes::EDGE_RATIO)
    .value("EQUIANGLE_SKEW", vtkMeshQuality::QualityMeasureTypes::EQUIANGLE_SKEW)
    .value("EQUIVOLUME_SKEW", vtkMeshQuality::QualityMeasureTypes::EQUIVOLUME_SKEW)
    .value("JACOBIAN", vtkMeshQuality::QualityMeasureTypes::JACOBIAN)
    .value("MAX_ANGLE", vtkMeshQuality::QualityMeasureTypes::MAX_ANGLE)
    .value("MAX_ASPECT_FROBENIUS", vtkMeshQuality::QualityMeasureTypes::MAX_ASPECT_FROBENIUS)
    .value("MAX_EDGE_RATIO", vtkMeshQuality::QualityMeasureTypes::MAX_EDGE_RATIO)
    .value("MAX_STRETCH", vtkMeshQuality::QualityMeasureTypes::MAX_STRETCH)
    .value("MEAN_ASPECT_FROBENIUS", vtkMeshQuality::QualityMeasureTypes::MEAN_ASPECT_FROBENIUS)
    .value("MEAN_RATIO", vtkMeshQuality::QualityMeasureTypes::MEAN_RATIO)
    .value("MED_ASPECT_FROBENIUS", vtkMeshQuality::QualityMeasureTypes::MED_ASPECT_FROBENIUS)
    .value("MIN_ANGLE", vtkMeshQuality::QualityMeasureTypes::MIN_ANGLE)
    .value("NODAL_JACOBIAN_RATIO", vtkMeshQuality::QualityMeasureTypes::NODAL_JACOBIAN_RATIO)
    .value("NORMALIZED_INRADIUS", vtkMeshQuality::QualityMeasureTypes::NORMALIZED_INRADIUS)
    .value("ODDY", vtkMeshQuality::QualityMeasureTypes::ODDY)
    .value("RADIUS_RATIO", vtkMeshQuality::QualityMeasureTypes::RADIUS_RATIO)
    .value("RELATIVE_SIZE_SQUARED", vtkMeshQuality::QualityMeasureTypes::RELATIVE_SIZE_SQUARED)
    .value("SCALED_JACOBIAN", vtkMeshQuality::QualityMeasureTypes::SCALED_JACOBIAN)
    .value("SHAPE", vtkMeshQuality::QualityMeasureTypes::SHAPE)
    .value("SHAPE_AND_SIZE", vtkMeshQuality::QualityMeasureTypes::SHAPE_AND_SIZE)
    .value("SHEAR", vtkMeshQuality::QualityMeasureTypes::SHEAR)
    .value("SHEAR_AND_SIZE", vtkMeshQuality::QualityMeasureTypes::SHEAR_AND_SIZE)
    .value("SKEW", vtkMeshQuality::QualityMeasureTypes::SKEW)
    .value("SQUISH_INDEX", vtkMeshQuality::QualityMeasureTypes::SQUISH_INDEX)
    .value("STRETCH", vtkMeshQuality::QualityMeasureTypes::STRETCH)
    .value("TAPER", vtkMeshQuality::QualityMeasureTypes::TAPER)
    .value("VOLUME", vtkMeshQuality::QualityMeasureTypes::VOLUME)
    .value("WARPAGE", vtkMeshQuality::QualityMeasureTypes::WARPAGE)
    .value("TOTAL_QUALITY_MEASURE_TYPES", vtkMeshQuality::QualityMeasureTypes::TOTAL_QUALITY_MEASURE_TYPES)
    .value("NONE", vtkMeshQuality::QualityMeasureTypes::NONE);
}
template<> void emscripten::internal::raw_destructor<vtkMeshQuality>(vtkMeshQuality * ptr){ ptr->Delete(); }
EMSCRIPTEN_BINDINGS(vtkMeshQuality_class) {
  using QualityMeasureTypes=vtkMeshQuality::QualityMeasureTypes;
  emscripten::class_<vtkMeshQuality, emscripten::base<vtkDataSetAlgorithm>>("vtkMeshQuality")
    .smart_ptr<vtkSmartPointer<vtkMeshQuality>>("vtkSmartPointer<vtkMeshQuality>")
    .constructor(&vtk::MakeVTKSmartPtr<vtkMeshQuality>)
    .class_function("IsTypeOf", emscripten::optional_override([]( const std::string & arg_0) -> int {  return vtkMeshQuality::IsTypeOf( arg_0.c_str());}))
    .function("IsA", emscripten::optional_override([](vtkMeshQuality& self, const std::string & arg_0) -> int {  return self.IsA( arg_0.c_str());}))
    .class_function("SafeDownCast", &vtkMeshQuality::SafeDownCast, emscripten::allow_raw_pointers())
    .function("NewInstance", &vtkMeshQuality::NewInstance, emscripten::allow_raw_pointers())
    .class_function("GetNumberOfGenerationsFromBaseType", emscripten::optional_override([]( const std::string & arg_0) -> int {  return vtkMeshQuality::GetNumberOfGenerationsFromBaseType( arg_0.c_str());}))
    .function("GetNumberOfGenerationsFromBase", emscripten::optional_override([](vtkMeshQuality& self, const std::string & arg_0) -> int {  return self.GetNumberOfGenerationsFromBase( arg_0.c_str());}))
    .function("SetSaveCellQuality", &vtkMeshQuality::SetSaveCellQuality)
    .function("GetSaveCellQuality", &vtkMeshQuality::GetSaveCellQuality)
    .function("SaveCellQualityOn", &vtkMeshQuality::SaveCellQualityOn)
    .function("SaveCellQualityOff", &vtkMeshQuality::SaveCellQualityOff)
    .function("SetLinearApproximation", &vtkMeshQuality::SetLinearApproximation)
    .function("GetLinearApproximation", &vtkMeshQuality::GetLinearApproximation)
    .function("LinearApproximationOn", &vtkMeshQuality::LinearApproximationOn)
    .function("LinearApproximationOff", &vtkMeshQuality::LinearApproximationOff)
    .function("SetTriangleQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, QualityMeasureTypes)>([](vtkMeshQuality& self, QualityMeasureTypes arg_0) -> void { return self.SetTriangleQualityMeasure( arg_0); }))
    .function("SetTriangleQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, int)>([](vtkMeshQuality& self, int arg_0) -> void { return self.SetTriangleQualityMeasure( arg_0); }))
    .function("GetTriangleQualityMeasure", &vtkMeshQuality::GetTriangleQualityMeasure)
    .function("SetTriangleQualityMeasureToArea", &vtkMeshQuality::SetTriangleQualityMeasureToArea)
    .function("SetTriangleQualityMeasureToEdgeRatio", &vtkMeshQuality::SetTriangleQualityMeasureToEdgeRatio)
    .function("SetTriangleQualityMeasureToAspectRatio", &vtkMeshQuality::SetTriangleQualityMeasureToAspectRatio)
    .function("SetTriangleQualityMeasureToRadiusRatio", &vtkMeshQuality::SetTriangleQualityMeasureToRadiusRatio)
    .function("SetTriangleQualityMeasureToAspectFrobenius", &vtkMeshQuality::SetTriangleQualityMeasureToAspectFrobenius)
    .function("SetTriangleQualityMeasureToMinAngle", &vtkMeshQuality::SetTriangleQualityMeasureToMinAngle)
    .function("SetTriangleQualityMeasureToMaxAngle", &vtkMeshQuality::SetTriangleQualityMeasureToMaxAngle)
    .function("SetTriangleQualityMeasureToCondition", &vtkMeshQuality::SetTriangleQualityMeasureToCondition)
    .function("SetTriangleQualityMeasureToScaledJacobian", &vtkMeshQuality::SetTriangleQualityMeasureToScaledJacobian)
    .function("SetTriangleQualityMeasureToRelativeSizeSquared", &vtkMeshQuality::SetTriangleQualityMeasureToRelativeSizeSquared)
    .function("SetTriangleQualityMeasureToShape", &vtkMeshQuality::SetTriangleQualityMeasureToShape)
    .function("SetTriangleQualityMeasureToShapeAndSize", &vtkMeshQuality::SetTriangleQualityMeasureToShapeAndSize)
    .function("SetTriangleQualityMeasureToDistortion", &vtkMeshQuality::SetTriangleQualityMeasureToDistortion)
    .function("SetTriangleQualityMeasureToEquiangleSkew", &vtkMeshQuality::SetTriangleQualityMeasureToEquiangleSkew)
    .function("SetTriangleQualityMeasureToNormalizedInradius", &vtkMeshQuality::SetTriangleQualityMeasureToNormalizedInradius)
    .function("SetQuadQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, QualityMeasureTypes)>([](vtkMeshQuality& self, QualityMeasureTypes arg_0) -> void { return self.SetQuadQualityMeasure( arg_0); }))
    .function("SetQuadQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, int)>([](vtkMeshQuality& self, int arg_0) -> void { return self.SetQuadQualityMeasure( arg_0); }))
    .function("GetQuadQualityMeasure", &vtkMeshQuality::GetQuadQualityMeasure)
    .function("SetQuadQualityMeasureToEdgeRatio", &vtkMeshQuality::SetQuadQualityMeasureToEdgeRatio)
    .function("SetQuadQualityMeasureToAspectRatio", &vtkMeshQuality::SetQuadQualityMeasureToAspectRatio)
    .function("SetQuadQualityMeasureToRadiusRatio", &vtkMeshQuality::SetQuadQualityMeasureToRadiusRatio)
    .function("SetQuadQualityMeasureToMedAspectFrobenius", &vtkMeshQuality::SetQuadQualityMeasureToMedAspectFrobenius)
    .function("SetQuadQualityMeasureToMaxAspectFrobenius", &vtkMeshQuality::SetQuadQualityMeasureToMaxAspectFrobenius)
    .function("SetQuadQualityMeasureToMaxEdgeRatio", &vtkMeshQuality::SetQuadQualityMeasureToMaxEdgeRatio)
    .function("SetQuadQualityMeasureToSkew", &vtkMeshQuality::SetQuadQualityMeasureToSkew)
    .function("SetQuadQualityMeasureToTaper", &vtkMeshQuality::SetQuadQualityMeasureToTaper)
    .function("SetQuadQualityMeasureToWarpage", &vtkMeshQuality::SetQuadQualityMeasureToWarpage)
    .function("SetQuadQualityMeasureToArea", &vtkMeshQuality::SetQuadQualityMeasureToArea)
    .function("SetQuadQualityMeasureToStretch", &vtkMeshQuality::SetQuadQualityMeasureToStretch)
    .function("SetQuadQualityMeasureToMinAngle", &vtkMeshQuality::SetQuadQualityMeasureToMinAngle)
    .function("SetQuadQualityMeasureToMaxAngle", &vtkMeshQuality::SetQuadQualityMeasureToMaxAngle)
    .function("SetQuadQualityMeasureToOddy", &vtkMeshQuality::SetQuadQualityMeasureToOddy)
    .function("SetQuadQualityMeasureToCondition", &vtkMeshQuality::SetQuadQualityMeasureToCondition)
    .function("SetQuadQualityMeasureToJacobian", &vtkMeshQuality::SetQuadQualityMeasureToJacobian)
    .function("SetQuadQualityMeasureToScaledJacobian", &vtkMeshQuality::SetQuadQualityMeasureToScaledJacobian)
    .function("SetQuadQualityMeasureToShear", &vtkMeshQuality::SetQuadQualityMeasureToShear)
    .function("SetQuadQualityMeasureToShape", &vtkMeshQuality::SetQuadQualityMeasureToShape)
    .function("SetQuadQualityMeasureToRelativeSizeSquared", &vtkMeshQuality::SetQuadQualityMeasureToRelativeSizeSquared)
    .function("SetQuadQualityMeasureToShapeAndSize", &vtkMeshQuality::SetQuadQualityMeasureToShapeAndSize)
    .function("SetQuadQualityMeasureToShearAndSize", &vtkMeshQuality::SetQuadQualityMeasureToShearAndSize)
    .function("SetQuadQualityMeasureToDistortion", &vtkMeshQuality::SetQuadQualityMeasureToDistortion)
    .function("SetQuadQualityMeasureToEquiangleSkew", &vtkMeshQuality::SetQuadQualityMeasureToEquiangleSkew)
    .function("SetTetQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, QualityMeasureTypes)>([](vtkMeshQuality& self, QualityMeasureTypes arg_0) -> void { return self.SetTetQualityMeasure( arg_0); }))
    .function("SetTetQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, int)>([](vtkMeshQuality& self, int arg_0) -> void { return self.SetTetQualityMeasure( arg_0); }))
    .function("GetTetQualityMeasure", &vtkMeshQuality::GetTetQualityMeasure)
    .function("SetTetQualityMeasureToEdgeRatio", &vtkMeshQuality::SetTetQualityMeasureToEdgeRatio)
    .function("SetTetQualityMeasureToAspectRatio", &vtkMeshQuality::SetTetQualityMeasureToAspectRatio)
    .function("SetTetQualityMeasureToRadiusRatio", &vtkMeshQuality::SetTetQualityMeasureToRadiusRatio)
    .function("SetTetQualityMeasureToAspectFrobenius", &vtkMeshQuality::SetTetQualityMeasureToAspectFrobenius)
    .function("SetTetQualityMeasureToMinAngle", &vtkMeshQuality::SetTetQualityMeasureToMinAngle)
    .function("SetTetQualityMeasureToCollapseRatio", &vtkMeshQuality::SetTetQualityMeasureToCollapseRatio)
    .function("SetTetQualityMeasureToAspectGamma", &vtkMeshQuality::SetTetQualityMeasureToAspectGamma)
    .function("SetTetQualityMeasureToVolume", &vtkMeshQuality::SetTetQualityMeasureToVolume)
    .function("SetTetQualityMeasureToCondition", &vtkMeshQuality::SetTetQualityMeasureToCondition)
    .function("SetTetQualityMeasureToJacobian", &vtkMeshQuality::SetTetQualityMeasureToJacobian)
    .function("SetTetQualityMeasureToScaledJacobian", &vtkMeshQuality::SetTetQualityMeasureToScaledJacobian)
    .function("SetTetQualityMeasureToShape", &vtkMeshQuality::SetTetQualityMeasureToShape)
    .function("SetTetQualityMeasureToRelativeSizeSquared", &vtkMeshQuality::SetTetQualityMeasureToRelativeSizeSquared)
    .function("SetTetQualityMeasureToShapeAndSize", &vtkMeshQuality::SetTetQualityMeasureToShapeAndSize)
    .function("SetTetQualityMeasureToDistortion", &vtkMeshQuality::SetTetQualityMeasureToDistortion)
    .function("SetTetQualityMeasureToEquiangleSkew", &vtkMeshQuality::SetTetQualityMeasureToEquiangleSkew)
    .function("SetTetQualityMeasureToEquivolumeSkew", &vtkMeshQuality::SetTetQualityMeasureToEquivolumeSkew)
    .function("SetTetQualityMeasureToMeanRatio", &vtkMeshQuality::SetTetQualityMeasureToMeanRatio)
    .function("SetTetQualityMeasureToNormalizedInradius", &vtkMeshQuality::SetTetQualityMeasureToNormalizedInradius)
    .function("SetTetQualityMeasureToSquishIndex", &vtkMeshQuality::SetTetQualityMeasureToSquishIndex)
    .function("SetPyramidQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, QualityMeasureTypes)>([](vtkMeshQuality& self, QualityMeasureTypes arg_0) -> void { return self.SetPyramidQualityMeasure( arg_0); }))
    .function("SetPyramidQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, int)>([](vtkMeshQuality& self, int arg_0) -> void { return self.SetPyramidQualityMeasure( arg_0); }))
    .function("GetPyramidQualityMeasure", &vtkMeshQuality::GetPyramidQualityMeasure)
    .function("SetPyramidQualityMeasureToEquiangleSkew", &vtkMeshQuality::SetPyramidQualityMeasureToEquiangleSkew)
    .function("SetPyramidQualityMeasureToJacobian", &vtkMeshQuality::SetPyramidQualityMeasureToJacobian)
    .function("SetPyramidQualityMeasureToScaledJacobian", &vtkMeshQuality::SetPyramidQualityMeasureToScaledJacobian)
    .function("SetPyramidQualityMeasureToShape", &vtkMeshQuality::SetPyramidQualityMeasureToShape)
    .function("SetPyramidQualityMeasureToVolume", &vtkMeshQuality::SetPyramidQualityMeasureToVolume)
    .function("SetWedgeQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, QualityMeasureTypes)>([](vtkMeshQuality& self, QualityMeasureTypes arg_0) -> void { return self.SetWedgeQualityMeasure( arg_0); }))
    .function("SetWedgeQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, int)>([](vtkMeshQuality& self, int arg_0) -> void { return self.SetWedgeQualityMeasure( arg_0); }))
    .function("GetWedgeQualityMeasure", &vtkMeshQuality::GetWedgeQualityMeasure)
    .function("SetWedgeQualityMeasureToCondition", &vtkMeshQuality::SetWedgeQualityMeasureToCondition)
    .function("SetWedgeQualityMeasureToDistortion", &vtkMeshQuality::SetWedgeQualityMeasureToDistortion)
    .function("SetWedgeQualityMeasureToEdgeRatio", &vtkMeshQuality::SetWedgeQualityMeasureToEdgeRatio)
    .function("SetWedgeQualityMeasureToEquiangleSkew", &vtkMeshQuality::SetWedgeQualityMeasureToEquiangleSkew)
    .function("SetWedgeQualityMeasureToJacobian", &vtkMeshQuality::SetWedgeQualityMeasureToJacobian)
    .function("SetWedgeQualityMeasureToMaxAspectFrobenius", &vtkMeshQuality::SetWedgeQualityMeasureToMaxAspectFrobenius)
    .function("SetWedgeQualityMeasureToMaxStretch", &vtkMeshQuality::SetWedgeQualityMeasureToMaxStretch)
    .function("SetWedgeQualityMeasureToMeanAspectFrobenius", &vtkMeshQuality::SetWedgeQualityMeasureToMeanAspectFrobenius)
    .function("SetWedgeQualityMeasureToScaledJacobian", &vtkMeshQuality::SetWedgeQualityMeasureToScaledJacobian)
    .function("SetWedgeQualityMeasureToShape", &vtkMeshQuality::SetWedgeQualityMeasureToShape)
    .function("SetWedgeQualityMeasureToVolume", &vtkMeshQuality::SetWedgeQualityMeasureToVolume)
    .function("SetHexQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, QualityMeasureTypes)>([](vtkMeshQuality& self, QualityMeasureTypes arg_0) -> void { return self.SetHexQualityMeasure( arg_0); }))
    .function("SetHexQualityMeasure", emscripten::select_overload<void(vtkMeshQuality&, int)>([](vtkMeshQuality& self, int arg_0) -> void { return self.SetHexQualityMeasure( arg_0); }))
    .function("GetHexQualityMeasure", &vtkMeshQuality::GetHexQualityMeasure)
    .function("SetHexQualityMeasureToEdgeRatio", &vtkMeshQuality::SetHexQualityMeasureToEdgeRatio)
    .function("SetHexQualityMeasureToMedAspectFrobenius", &vtkMeshQuality::SetHexQualityMeasureToMedAspectFrobenius)
    .function("SetHexQualityMeasureToMaxAspectFrobenius", &vtkMeshQuality::SetHexQualityMeasureToMaxAspectFrobenius)
    .function("SetHexQualityMeasureToMaxEdgeRatio", &vtkMeshQuality::SetHexQualityMeasureToMaxEdgeRatio)
    .function("SetHexQualityMeasureToSkew", &vtkMeshQuality::SetHexQualityMeasureToSkew)
    .function("SetHexQualityMeasureToTaper", &vtkMeshQuality::SetHexQualityMeasureToTaper)
    .function("SetHexQualityMeasureToVolume", &vtkMeshQuality::SetHexQualityMeasureToVolume)
    .function("SetHexQualityMeasureToStretch", &vtkMeshQuality::SetHexQualityMeasureToStretch)
    .function("SetHexQualityMeasureToDiagonal", &vtkMeshQuality::SetHexQualityMeasureToDiagonal)
    .function("SetHexQualityMeasureToDimension", &vtkMeshQuality::SetHexQualityMeasureToDimension)
    .function("SetHexQualityMeasureToOddy", &vtkMeshQuality::SetHexQualityMeasureToOddy)
    .function("SetHexQualityMeasureToCondition", &vtkMeshQuality::SetHexQualityMeasureToCondition)
    .function("SetHexQualityMeasureToJacobian", &vtkMeshQuality::SetHexQualityMeasureToJacobian)
    .function("SetHexQualityMeasureToScaledJacobian", &vtkMeshQuality::SetHexQualityMeasureToScaledJacobian)
    .function("SetHexQualityMeasureToShear", &vtkMeshQuality::SetHexQualityMeasureToShear)
    .function("SetHexQualityMeasureToShape", &vtkMeshQuality::SetHexQualityMeasureToShape)
    .function("SetHexQualityMeasureToRelativeSizeSquared", &vtkMeshQuality::SetHexQualityMeasureToRelativeSizeSquared)
    .function("SetHexQualityMeasureToShapeAndSize", &vtkMeshQuality::SetHexQualityMeasureToShapeAndSize)
    .function("SetHexQualityMeasureToShearAndSize", &vtkMeshQuality::SetHexQualityMeasureToShearAndSize)
    .function("SetHexQualityMeasureToDistortion", &vtkMeshQuality::SetHexQualityMeasureToDistortion)
    .function("SetHexQualityMeasureToEquiangleSkew", &vtkMeshQuality::SetHexQualityMeasureToEquiangleSkew)
    .function("SetHexQualityMeasureToNodalJacobianRatio", &vtkMeshQuality::SetHexQualityMeasureToNodalJacobianRatio)
    .class_function("TriangleArea", &vtkMeshQuality::TriangleArea, emscripten::allow_raw_pointers())
    .class_function("TriangleEdgeRatio", &vtkMeshQuality::TriangleEdgeRatio, emscripten::allow_raw_pointers())
    .class_function("TriangleAspectRatio", &vtkMeshQuality::TriangleAspectRatio, emscripten::allow_raw_pointers())
    .class_function("TriangleRadiusRatio", &vtkMeshQuality::TriangleRadiusRatio, emscripten::allow_raw_pointers())
    .class_function("TriangleAspectFrobenius", &vtkMeshQuality::TriangleAspectFrobenius, emscripten::allow_raw_pointers())
    .class_function("TriangleMinAngle", &vtkMeshQuality::TriangleMinAngle, emscripten::allow_raw_pointers())
    .class_function("TriangleMaxAngle", &vtkMeshQuality::TriangleMaxAngle, emscripten::allow_raw_pointers())
    .class_function("TriangleCondition", &vtkMeshQuality::TriangleCondition, emscripten::allow_raw_pointers())
    .class_function("TriangleScaledJacobian", &vtkMeshQuality::TriangleScaledJacobian, emscripten::allow_raw_pointers())
    .class_function("TriangleRelativeSizeSquared", &vtkMeshQuality::TriangleRelativeSizeSquared, emscripten::allow_raw_pointers())
    .class_function("TriangleShape", &vtkMeshQuality::TriangleShape, emscripten::allow_raw_pointers())
    .class_function("TriangleShapeAndSize", &vtkMeshQuality::TriangleShapeAndSize, emscripten::allow_raw_pointers())
    .class_function("TriangleDistortion", &vtkMeshQuality::TriangleDistortion, emscripten::allow_raw_pointers())
    .class_function("TriangleEquiangleSkew", &vtkMeshQuality::TriangleEquiangleSkew, emscripten::allow_raw_pointers())
    .class_function("TriangleNormalizedInradius", &vtkMeshQuality::TriangleNormalizedInradius, emscripten::allow_raw_pointers())
    .class_function("QuadEdgeRatio", &vtkMeshQuality::QuadEdgeRatio, emscripten::allow_raw_pointers())
    .class_function("QuadAspectRatio", &vtkMeshQuality::QuadAspectRatio, emscripten::allow_raw_pointers())
    .class_function("QuadRadiusRatio", &vtkMeshQuality::QuadRadiusRatio, emscripten::allow_raw_pointers())
    .class_function("QuadMedAspectFrobenius", &vtkMeshQuality::QuadMedAspectFrobenius, emscripten::allow_raw_pointers())
    .class_function("QuadMaxAspectFrobenius", &vtkMeshQuality::QuadMaxAspectFrobenius, emscripten::allow_raw_pointers())
    .class_function("QuadMinAngle", &vtkMeshQuality::QuadMinAngle, emscripten::allow_raw_pointers())
    .class_function("QuadMaxEdgeRatio", &vtkMeshQuality::QuadMaxEdgeRatio, emscripten::allow_raw_pointers())
    .class_function("QuadSkew", &vtkMeshQuality::QuadSkew, emscripten::allow_raw_pointers())
    .class_function("QuadTaper", &vtkMeshQuality::QuadTaper, emscripten::allow_raw_pointers())
    .class_function("QuadWarpage", &vtkMeshQuality::QuadWarpage, emscripten::allow_raw_pointers())
    .class_function("QuadArea", &vtkMeshQuality::QuadArea, emscripten::allow_raw_pointers())
    .class_function("QuadStretch", &vtkMeshQuality::QuadStretch, emscripten::allow_raw_pointers())
    .class_function("QuadMaxAngle", &vtkMeshQuality::QuadMaxAngle, emscripten::allow_raw_pointers())
    .class_function("QuadOddy", &vtkMeshQuality::QuadOddy, emscripten::allow_raw_pointers())
    .class_function("QuadCondition", &vtkMeshQuality::QuadCondition, emscripten::allow_raw_pointers())
    .class_function("QuadJacobian", &vtkMeshQuality::QuadJacobian, emscripten::allow_raw_pointers())
    .class_function("QuadScaledJacobian", &vtkMeshQuality::QuadScaledJacobian, emscripten::allow_raw_pointers())
    .class_function("QuadShear", &vtkMeshQuality::QuadShear, emscripten::allow_raw_pointers())
    .class_function("QuadShape", &vtkMeshQuality::QuadShape, emscripten::allow_raw_pointers())
    .class_function("QuadRelativeSizeSquared", &vtkMeshQuality::QuadRelativeSizeSquared, emscripten::allow_raw_pointers())
    .class_function("QuadShapeAndSize", &vtkMeshQuality::QuadShapeAndSize, emscripten::allow_raw_pointers())
    .class_function("QuadShearAndSize", &vtkMeshQuality::QuadShearAndSize, emscripten::allow_raw_pointers())
    .class_function("QuadDistortion", &vtkMeshQuality::QuadDistortion, emscripten::allow_raw_pointers())
    .class_function("QuadEquiangleSkew", &vtkMeshQuality::QuadEquiangleSkew, emscripten::allow_raw_pointers())
    .class_function("TetEdgeRatio", &vtkMeshQuality::TetEdgeRatio, emscripten::allow_raw_pointers())
    .class_function("TetAspectRatio", &vtkMeshQuality::TetAspectRatio, emscripten::allow_raw_pointers())
    .class_function("TetRadiusRatio", &vtkMeshQuality::TetRadiusRatio, emscripten::allow_raw_pointers())
    .class_function("TetAspectFrobenius", &vtkMeshQuality::TetAspectFrobenius, emscripten::allow_raw_pointers())
    .class_function("TetMinAngle", &vtkMeshQuality::TetMinAngle, emscripten::allow_raw_pointers())
    .class_function("TetCollapseRatio", &vtkMeshQuality::TetCollapseRatio, emscripten::allow_raw_pointers())
    .class_function("TetAspectGamma", &vtkMeshQuality::TetAspectGamma, emscripten::allow_raw_pointers())
    .class_function("TetVolume", &vtkMeshQuality::TetVolume, emscripten::allow_raw_pointers())
    .class_function("TetCondition", &vtkMeshQuality::TetCondition, emscripten::allow_raw_pointers())
    .class_function("TetJacobian", &vtkMeshQuality::TetJacobian, emscripten::allow_raw_pointers())
    .class_function("TetScaledJacobian", &vtkMeshQuality::TetScaledJacobian, emscripten::allow_raw_pointers())
    .class_function("TetShape", &vtkMeshQuality::TetShape, emscripten::allow_raw_pointers())
    .class_function("TetRelativeSizeSquared", &vtkMeshQuality::TetRelativeSizeSquared, emscripten::allow_raw_pointers())
    .class_function("TetShapeAndSize", &vtkMeshQuality::TetShapeAndSize, emscripten::allow_raw_pointers())
    .class_function("TetDistortion", &vtkMeshQuality::TetDistortion, emscripten::allow_raw_pointers())
    .class_function("TetEquiangleSkew", &vtkMeshQuality::TetEquiangleSkew, emscripten::allow_raw_pointers())
    .class_function("TetEquivolumeSkew", &vtkMeshQuality::TetEquivolumeSkew, emscripten::allow_raw_pointers())
    .class_function("TetMeanRatio", &vtkMeshQuality::TetMeanRatio, emscripten::allow_raw_pointers())
    .class_function("TetNormalizedInradius", &vtkMeshQuality::TetNormalizedInradius, emscripten::allow_raw_pointers())
    .class_function("TetSquishIndex", &vtkMeshQuality::TetSquishIndex, emscripten::allow_raw_pointers())
    .class_function("PyramidEquiangleSkew", &vtkMeshQuality::PyramidEquiangleSkew, emscripten::allow_raw_pointers())
    .class_function("PyramidJacobian", &vtkMeshQuality::PyramidJacobian, emscripten::allow_raw_pointers())
    .class_function("PyramidScaledJacobian", &vtkMeshQuality::PyramidScaledJacobian, emscripten::allow_raw_pointers())
    .class_function("PyramidShape", &vtkMeshQuality::PyramidShape, emscripten::allow_raw_pointers())
    .class_function("PyramidVolume", &vtkMeshQuality::PyramidVolume, emscripten::allow_raw_pointers())
    .class_function("WedgeCondition", &vtkMeshQuality::WedgeCondition, emscripten::allow_raw_pointers())
    .class_function("WedgeDistortion", &vtkMeshQuality::WedgeDistortion, emscripten::allow_raw_pointers())
    .class_function("WedgeEdgeRatio", &vtkMeshQuality::WedgeEdgeRatio, emscripten::allow_raw_pointers())
    .class_function("WedgeEquiangleSkew", &vtkMeshQuality::WedgeEquiangleSkew, emscripten::allow_raw_pointers())
    .class_function("WedgeJacobian", &vtkMeshQuality::WedgeJacobian, emscripten::allow_raw_pointers())
    .class_function("WedgeMaxAspectFrobenius", &vtkMeshQuality::WedgeMaxAspectFrobenius, emscripten::allow_raw_pointers())
    .class_function("WedgeMaxStretch", &vtkMeshQuality::WedgeMaxStretch, emscripten::allow_raw_pointers())
    .class_function("WedgeMeanAspectFrobenius", &vtkMeshQuality::WedgeMeanAspectFrobenius, emscripten::allow_raw_pointers())
    .class_function("WedgeScaledJacobian", &vtkMeshQuality::WedgeScaledJacobian, emscripten::allow_raw_pointers())
    .class_function("WedgeShape", &vtkMeshQuality::WedgeShape, emscripten::allow_raw_pointers())
    .class_function("WedgeVolume", &vtkMeshQuality::WedgeVolume, emscripten::allow_raw_pointers())
    .class_function("HexEdgeRatio", &vtkMeshQuality::HexEdgeRatio, emscripten::allow_raw_pointers())
    .class_function("HexMedAspectFrobenius", &vtkMeshQuality::HexMedAspectFrobenius, emscripten::allow_raw_pointers())
    .class_function("HexMaxAspectFrobenius", &vtkMeshQuality::HexMaxAspectFrobenius, emscripten::allow_raw_pointers())
    .class_function("HexMaxEdgeRatio", &vtkMeshQuality::HexMaxEdgeRatio, emscripten::allow_raw_pointers())
    .class_function("HexSkew", &vtkMeshQuality::HexSkew, emscripten::allow_raw_pointers())
    .class_function("HexTaper", &vtkMeshQuality::HexTaper, emscripten::allow_raw_pointers())
    .class_function("HexVolume", &vtkMeshQuality::HexVolume, emscripten::allow_raw_pointers())
    .class_function("HexStretch", &vtkMeshQuality::HexStretch, emscripten::allow_raw_pointers())
    .class_function("HexDiagonal", &vtkMeshQuality::HexDiagonal, emscripten::allow_raw_pointers())
    .class_function("HexDimension", &vtkMeshQuality::HexDimension, emscripten::allow_raw_pointers())
    .class_function("HexOddy", &vtkMeshQuality::HexOddy, emscripten::allow_raw_pointers())
    .class_function("HexCondition", &vtkMeshQuality::HexCondition, emscripten::allow_raw_pointers())
    .class_function("HexJacobian", &vtkMeshQuality::HexJacobian, emscripten::allow_raw_pointers())
    .class_function("HexScaledJacobian", &vtkMeshQuality::HexScaledJacobian, emscripten::allow_raw_pointers())
    .class_function("HexShear", &vtkMeshQuality::HexShear, emscripten::allow_raw_pointers())
    .class_function("HexShape", &vtkMeshQuality::HexShape, emscripten::allow_raw_pointers())
    .class_function("HexRelativeSizeSquared", &vtkMeshQuality::HexRelativeSizeSquared, emscripten::allow_raw_pointers())
    .class_function("HexShapeAndSize", &vtkMeshQuality::HexShapeAndSize, emscripten::allow_raw_pointers())
    .class_function("HexShearAndSize", &vtkMeshQuality::HexShearAndSize, emscripten::allow_raw_pointers())
    .class_function("HexDistortion", &vtkMeshQuality::HexDistortion, emscripten::allow_raw_pointers())
    .class_function("HexEquiangleSkew", &vtkMeshQuality::HexEquiangleSkew, emscripten::allow_raw_pointers())
    .class_function("HexNodalJacobianRatio", &vtkMeshQuality::HexNodalJacobianRatio, emscripten::allow_raw_pointers())
    .function("SetRatio", &vtkMeshQuality::SetRatio)
    .function("GetRatio", &vtkMeshQuality::GetRatio)
    .function("RatioOn", &vtkMeshQuality::RatioOn)
    .function("RatioOff", &vtkMeshQuality::RatioOff);
}
