// JavaScript wrapper for vtkRandomAttributeGenerator with embind 
//
// This file was auto-generated using :
/*
node /home/jmh/github/VTKCMake/build/library/VTK-prefix/src/VTK-build/bin/vtkWrapJavaScript.js \
 @/home/jmh/github/VTKCMake/build/library/VTK-prefix/src/VTK-build/CMakeFiles/vtkFiltersGeneral.js/vtkFiltersGeneral.js.Release.args \
 -o \
 /home/jmh/github/VTKCMake/build/library/VTK-prefix/src/VTK-build/CMakeFiles/vtkFiltersGeneral.js/vtkRandomAttributeGeneratorEmbinding.cxx \
 /home/jmh/github/vtk/Filters/General/vtkRandomAttributeGenerator.h
*/
#include "vtkEmbindSmartPointerTrait.h"
#include <emscripten.h>
#include <string>
#include "vtkVariant.h"
#include "vtkObjectBase.h"
#include "vtkIndent.h"
#include "vtkRandomAttributeGenerator.h"

template<> void emscripten::internal::raw_destructor<vtkRandomAttributeGenerator>(vtkRandomAttributeGenerator * ptr){ ptr->Delete(); }
EMSCRIPTEN_BINDINGS(vtkRandomAttributeGenerator_class) {
  emscripten::class_<vtkRandomAttributeGenerator, emscripten::base<vtkPassInputTypeAlgorithm>>("vtkRandomAttributeGenerator")
    .smart_ptr<vtkSmartPointer<vtkRandomAttributeGenerator>>("vtkSmartPointer<vtkRandomAttributeGenerator>")
    .constructor(&vtk::MakeAvtkSmartPointer<vtkRandomAttributeGenerator>)
    .class_function("IsTypeOf", emscripten::optional_override([]( const std::string & arg_0) -> int {  return vtkRandomAttributeGenerator::IsTypeOf( arg_0.c_str());}))
    .function("IsA", emscripten::optional_override([](vtkRandomAttributeGenerator& self, const std::string & arg_0) -> int {  return self.IsA( arg_0.c_str());}))
    .class_function("SafeDownCast", &vtkRandomAttributeGenerator::SafeDownCast, emscripten::allow_raw_pointers())
    .function("NewInstance", &vtkRandomAttributeGenerator::NewInstance, emscripten::allow_raw_pointers())
    .class_function("GetNumberOfGenerationsFromBaseType", emscripten::optional_override([]( const std::string & arg_0) -> int {  return vtkRandomAttributeGenerator::GetNumberOfGenerationsFromBaseType( arg_0.c_str());}))
    .function("GetNumberOfGenerationsFromBase", emscripten::optional_override([](vtkRandomAttributeGenerator& self, const std::string & arg_0) -> int {  return self.GetNumberOfGenerationsFromBase( arg_0.c_str());}))
    .function("SetDataType", &vtkRandomAttributeGenerator::SetDataType)
    .function("SetDataTypeToBit", &vtkRandomAttributeGenerator::SetDataTypeToBit)
    .function("SetDataTypeToChar", &vtkRandomAttributeGenerator::SetDataTypeToChar)
    .function("SetDataTypeToUnsignedChar", &vtkRandomAttributeGenerator::SetDataTypeToUnsignedChar)
    .function("SetDataTypeToShort", &vtkRandomAttributeGenerator::SetDataTypeToShort)
    .function("SetDataTypeToUnsignedShort", &vtkRandomAttributeGenerator::SetDataTypeToUnsignedShort)
    .function("SetDataTypeToInt", &vtkRandomAttributeGenerator::SetDataTypeToInt)
    .function("SetDataTypeToUnsignedInt", &vtkRandomAttributeGenerator::SetDataTypeToUnsignedInt)
    .function("SetDataTypeToLong", &vtkRandomAttributeGenerator::SetDataTypeToLong)
    .function("SetDataTypeToLongLong", &vtkRandomAttributeGenerator::SetDataTypeToLongLong)
    .function("SetDataTypeToUnsignedLong", &vtkRandomAttributeGenerator::SetDataTypeToUnsignedLong)
    .function("SetDataTypeToUnsignedLongLong", &vtkRandomAttributeGenerator::SetDataTypeToUnsignedLongLong)
    .function("SetDataTypeToIdType", &vtkRandomAttributeGenerator::SetDataTypeToIdType)
    .function("SetDataTypeToFloat", &vtkRandomAttributeGenerator::SetDataTypeToFloat)
    .function("SetDataTypeToDouble", &vtkRandomAttributeGenerator::SetDataTypeToDouble)
    .function("GetDataType", &vtkRandomAttributeGenerator::GetDataType)
    .function("SetNumberOfComponents", &vtkRandomAttributeGenerator::SetNumberOfComponents)
    .function("GetNumberOfComponentsMinValue", &vtkRandomAttributeGenerator::GetNumberOfComponentsMinValue)
    .function("GetNumberOfComponentsMaxValue", &vtkRandomAttributeGenerator::GetNumberOfComponentsMaxValue)
    .function("GetNumberOfComponents", &vtkRandomAttributeGenerator::GetNumberOfComponents)
    .function("SetMinimumComponentValue", &vtkRandomAttributeGenerator::SetMinimumComponentValue)
    .function("GetMinimumComponentValue", &vtkRandomAttributeGenerator::GetMinimumComponentValue)
    .function("SetComponentRange", &vtkRandomAttributeGenerator::SetComponentRange)
    .function("SetMaximumComponentValue", &vtkRandomAttributeGenerator::SetMaximumComponentValue)
    .function("GetMaximumComponentValue", &vtkRandomAttributeGenerator::GetMaximumComponentValue)
    .function("SetNumberOfTuples", &vtkRandomAttributeGenerator::SetNumberOfTuples)
    .function("GetNumberOfTuplesMinValue", &vtkRandomAttributeGenerator::GetNumberOfTuplesMinValue)
    .function("GetNumberOfTuplesMaxValue", &vtkRandomAttributeGenerator::GetNumberOfTuplesMaxValue)
    .function("GetNumberOfTuples", &vtkRandomAttributeGenerator::GetNumberOfTuples)
    .function("SetGeneratePointScalars", &vtkRandomAttributeGenerator::SetGeneratePointScalars)
    .function("GetGeneratePointScalars", &vtkRandomAttributeGenerator::GetGeneratePointScalars)
    .function("GeneratePointScalarsOn", &vtkRandomAttributeGenerator::GeneratePointScalarsOn)
    .function("GeneratePointScalarsOff", &vtkRandomAttributeGenerator::GeneratePointScalarsOff)
    .function("SetGeneratePointVectors", &vtkRandomAttributeGenerator::SetGeneratePointVectors)
    .function("GetGeneratePointVectors", &vtkRandomAttributeGenerator::GetGeneratePointVectors)
    .function("GeneratePointVectorsOn", &vtkRandomAttributeGenerator::GeneratePointVectorsOn)
    .function("GeneratePointVectorsOff", &vtkRandomAttributeGenerator::GeneratePointVectorsOff)
    .function("SetGeneratePointNormals", &vtkRandomAttributeGenerator::SetGeneratePointNormals)
    .function("GetGeneratePointNormals", &vtkRandomAttributeGenerator::GetGeneratePointNormals)
    .function("GeneratePointNormalsOn", &vtkRandomAttributeGenerator::GeneratePointNormalsOn)
    .function("GeneratePointNormalsOff", &vtkRandomAttributeGenerator::GeneratePointNormalsOff)
    .function("SetGeneratePointTensors", &vtkRandomAttributeGenerator::SetGeneratePointTensors)
    .function("GetGeneratePointTensors", &vtkRandomAttributeGenerator::GetGeneratePointTensors)
    .function("GeneratePointTensorsOn", &vtkRandomAttributeGenerator::GeneratePointTensorsOn)
    .function("GeneratePointTensorsOff", &vtkRandomAttributeGenerator::GeneratePointTensorsOff)
    .function("SetGeneratePointTCoords", &vtkRandomAttributeGenerator::SetGeneratePointTCoords)
    .function("GetGeneratePointTCoords", &vtkRandomAttributeGenerator::GetGeneratePointTCoords)
    .function("GeneratePointTCoordsOn", &vtkRandomAttributeGenerator::GeneratePointTCoordsOn)
    .function("GeneratePointTCoordsOff", &vtkRandomAttributeGenerator::GeneratePointTCoordsOff)
    .function("SetGeneratePointArray", &vtkRandomAttributeGenerator::SetGeneratePointArray)
    .function("GetGeneratePointArray", &vtkRandomAttributeGenerator::GetGeneratePointArray)
    .function("GeneratePointArrayOn", &vtkRandomAttributeGenerator::GeneratePointArrayOn)
    .function("GeneratePointArrayOff", &vtkRandomAttributeGenerator::GeneratePointArrayOff)
    .function("SetGenerateCellScalars", &vtkRandomAttributeGenerator::SetGenerateCellScalars)
    .function("GetGenerateCellScalars", &vtkRandomAttributeGenerator::GetGenerateCellScalars)
    .function("GenerateCellScalarsOn", &vtkRandomAttributeGenerator::GenerateCellScalarsOn)
    .function("GenerateCellScalarsOff", &vtkRandomAttributeGenerator::GenerateCellScalarsOff)
    .function("SetGenerateCellVectors", &vtkRandomAttributeGenerator::SetGenerateCellVectors)
    .function("GetGenerateCellVectors", &vtkRandomAttributeGenerator::GetGenerateCellVectors)
    .function("GenerateCellVectorsOn", &vtkRandomAttributeGenerator::GenerateCellVectorsOn)
    .function("GenerateCellVectorsOff", &vtkRandomAttributeGenerator::GenerateCellVectorsOff)
    .function("SetGenerateCellNormals", &vtkRandomAttributeGenerator::SetGenerateCellNormals)
    .function("GetGenerateCellNormals", &vtkRandomAttributeGenerator::GetGenerateCellNormals)
    .function("GenerateCellNormalsOn", &vtkRandomAttributeGenerator::GenerateCellNormalsOn)
    .function("GenerateCellNormalsOff", &vtkRandomAttributeGenerator::GenerateCellNormalsOff)
    .function("SetGenerateCellTensors", &vtkRandomAttributeGenerator::SetGenerateCellTensors)
    .function("GetGenerateCellTensors", &vtkRandomAttributeGenerator::GetGenerateCellTensors)
    .function("GenerateCellTensorsOn", &vtkRandomAttributeGenerator::GenerateCellTensorsOn)
    .function("GenerateCellTensorsOff", &vtkRandomAttributeGenerator::GenerateCellTensorsOff)
    .function("SetGenerateCellTCoords", &vtkRandomAttributeGenerator::SetGenerateCellTCoords)
    .function("GetGenerateCellTCoords", &vtkRandomAttributeGenerator::GetGenerateCellTCoords)
    .function("GenerateCellTCoordsOn", &vtkRandomAttributeGenerator::GenerateCellTCoordsOn)
    .function("GenerateCellTCoordsOff", &vtkRandomAttributeGenerator::GenerateCellTCoordsOff)
    .function("SetGenerateCellArray", &vtkRandomAttributeGenerator::SetGenerateCellArray)
    .function("GetGenerateCellArray", &vtkRandomAttributeGenerator::GetGenerateCellArray)
    .function("GenerateCellArrayOn", &vtkRandomAttributeGenerator::GenerateCellArrayOn)
    .function("GenerateCellArrayOff", &vtkRandomAttributeGenerator::GenerateCellArrayOff)
    .function("SetGenerateFieldArray", &vtkRandomAttributeGenerator::SetGenerateFieldArray)
    .function("GetGenerateFieldArray", &vtkRandomAttributeGenerator::GetGenerateFieldArray)
    .function("GenerateFieldArrayOn", &vtkRandomAttributeGenerator::GenerateFieldArrayOn)
    .function("GenerateFieldArrayOff", &vtkRandomAttributeGenerator::GenerateFieldArrayOff)
    .function("SetAttributesConstantPerBlock", &vtkRandomAttributeGenerator::SetAttributesConstantPerBlock)
    .function("GetAttributesConstantPerBlock", &vtkRandomAttributeGenerator::GetAttributesConstantPerBlock)
    .function("AttributesConstantPerBlockOn", &vtkRandomAttributeGenerator::AttributesConstantPerBlockOn)
    .function("AttributesConstantPerBlockOff", &vtkRandomAttributeGenerator::AttributesConstantPerBlockOff)
    .function("GenerateAllPointDataOn", &vtkRandomAttributeGenerator::GenerateAllPointDataOn)
    .function("GenerateAllPointDataOff", &vtkRandomAttributeGenerator::GenerateAllPointDataOff)
    .function("GenerateAllCellDataOn", &vtkRandomAttributeGenerator::GenerateAllCellDataOn)
    .function("GenerateAllCellDataOff", &vtkRandomAttributeGenerator::GenerateAllCellDataOff)
    .function("GenerateAllDataOn", &vtkRandomAttributeGenerator::GenerateAllDataOn)
    .function("GenerateAllDataOff", &vtkRandomAttributeGenerator::GenerateAllDataOff);
}
